name: Bug report
description: Reportar un problema
title: "bug: "
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: Descripción del problema
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
